### ISSUE TITLE
Backend Geral - Validacao e permissionamento por perfil

### ISSUE THREAD

**Issue by aparizotoimpacta** [aparizotoimpacta/ozomali#25]
Definir as regras de acesso:

Admin pode acessar tudo
lojista definir escopo
estoque definir escopo

**Comment by sayuri1810** [comment]
Admininstrador
- permissao de fazer qualquer operacao

Vendedor 
- retirar itens do estoque
- retirar relatorios

Estoquista 
- adicionar produto no estoque e cadastrar novos/alterar produtos
- mudar precos de compra
- retirar relatorios
