### ISSUE TITLE
Relatorio de Vendas

### ISSUE THREAD

**Issue by aparizotoimpacta** [aparizotoimpacta/ozomali#29]

**Comment by sayuri1810** [comment]
Exemplo de retorno do report
{
	"data": [
		{"periodo": "Jan/20", "Vendas": 8522.54, "Compras": 5212.11, "Saldo": 3310.43, "ticket_medio": },
		{"periodo": "Fev/20", "Vendas": 3522.54, "Compras": 1212.11, "Saldo": 2310.43},
		{"periodo": "Mar/20", "Vendas": 1522.54, "Compras": 212.11, "Saldo": 1310.43}
	]
}
